MODEL: "resnet18"
OUT_DIM: 5
LOSS: "triplet"
MARGIN: 2.0
# Applies to MarginLoss only
LOSS_LAMBDA: 0.5
TRAIN_FILE: "train_1.csv"
DATASET_N: 3
EXCLUDE_WHALE: True
INCLUDE_BOXES: True
IMAGE_SIZE: 298
# TRANSFORMS: "CPad|Resize|RandomCrop"
BOXTRANSFORMS: "Square"
TRANSFORMS: "PIL|Grey|Pad|Rotate|RandomCrop"
PAIR_SPLIT_P: 0.5
BATCH_SIZE: 24
EVAL_BATCH_SIZE: 64
EPOCHS: 25
OPTIMIZER: "sgd"
LR: 0.001
MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001
GAMMA: 0.5
ALPHA: 0.8
REINDEX_INTERVAL: 5
EVAL_INTERVAL: 1
TEST_SIZE: 0.1
SEED: 42
